spring.datasource.url=jdbc:postgresql://localhost:5432/taxonomydb
spring.datasource.username=taxonomyuser
spring.datasource.password=taxonomypass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true